### ISSUE TITLE
25/7 Bug - Issue with Query to Backend

### ISSUE THREAD

**Issue by aerodromic** [xmlew/UniMod#24]
Warning: useEffect received a final argument that is not an array (instead, received `string`). When specified, the final argument must be an array.
    at DashboardApp (http://localhost:3000/static/js/bundle.js:4594:76)
    at Outlet (http://localhost:3000/static/js/bundle.js:138902:26)
    at div
    at http://localhost:3000/static/js/bundle.js:11527:66
    at div
    at http://localhost:3000/static/js/bundle.js:11527:66
    at DashboardLayout (http://localhost:3000/static/js/bundle.js:3911:74)
    at Router (http://localhost:3000/static/js/bundle.js:5870:70)
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:41597:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:41304:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:41617:5)
    at StyledEngineProvider (http://localhost:3000/static/js/bundle.js:41489:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:9488:5)
    at App
    at Router (http://localhost:3000/static/js/bundle.js:138927:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:137737:5)
    at r (http://localhost:3000/static/js/bundle.js:136174:19)

**Comment by aerodromic** [comment]
The heroku app https://unimod.herokuapp.com// keeps crashing when I try to reach it with a GET request.

**Comment by aerodromic** [comment]
After debugging and error catching, the server stops crashing from data overflow.
